# Generated by Django 5.0.7 on 2024-09-13 15:28

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobmodel",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="jobmodel",
            name="last_updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="jobmodel",
            name="status",
            field=models.CharField(max_length=32),
        ),
    ]
