# Generated by Django 5.0.7 on 2024-07-28 14:26

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="About title"
                    ),
                ),
                ("text", models.TextField(verbose_name="About text")),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "About",
            },
        ),
        migrations.CreateModel(
            name="ColorFont",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[("#000000", "black"), ("#FFFFFF", "white")],
                        max_length=16,
                        unique=True,
                        verbose_name="Color",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OurResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Results description"),
                ),
            ],
            options={
                "verbose_name": "Our results",
                "verbose_name_plural": "Our results",
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(max_length=16, verbose_name="WhatsApp"),
                ),
                (
                    "phone",
                    models.CharField(max_length=15, verbose_name="Phone"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AboutBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_title",
                    models.CharField(max_length=100, verbose_name="Title 1"),
                ),
                (
                    "first_description",
                    models.TextField(verbose_name="Subtext for Title 1"),
                ),
                (
                    "second_title",
                    models.CharField(max_length=100, verbose_name="Title 2"),
                ),
                (
                    "second_description",
                    models.TextField(verbose_name="Subtext for Title 2"),
                ),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="landing.about",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OurResultsPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="results/", verbose_name="Result photo"
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_photos",
                        to="landing.ourresults",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Service name"
                    ),
                ),
                (
                    "discount_message",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Discount message",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="service/", verbose_name="Service image"
                    ),
                ),
                (
                    "font_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="landing.colorfont",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="landing.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.CreateModel(
            name="ServiceDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality_title",
                    models.CharField(
                        max_length=100, verbose_name="Service quality title"
                    ),
                ),
                (
                    "quality_text",
                    models.TextField(verbose_name="Service quality text"),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_detail",
                        to="landing.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service detail",
                "verbose_name_plural": "Service details",
            },
        ),
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Advantage title"
                    ),
                ),
                (
                    "text",
                    models.TextField(verbose_name="Advantage description"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advantage",
                        to="landing.servicedetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advantage",
                "verbose_name_plural": "Advantages",
            },
        ),
        migrations.AddField(
            model_name="ourresults",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="landing.site",
            ),
        ),
        migrations.CreateModel(
            name="MainScreen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Title"),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="Above the title",
                        verbose_name="Description",
                    ),
                ),
                (
                    "subtext",
                    models.TextField(
                        blank=True,
                        help_text="Under the title",
                        verbose_name="Substext",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_screen",
                        to="landing.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Screen",
                "verbose_name_plural": "Main Screen",
            },
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "operating_mode",
                    models.CharField(
                        max_length=32, verbose_name="Operating mode"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=64, verbose_name="company address"
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footer",
                        to="landing.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer",
                "verbose_name_plural": "Footer",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Answer")),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq",
                        to="landing.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
            },
        ),
        migrations.AddField(
            model_name="about",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="about",
                to="landing.site",
            ),
        ),
    ]
