# Generated by Django 5.0.7 on 2024-08-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='site',
            name='whatsapp',
            field=models.CharField(max_length=256, verbose_name='WhatsApp'),
        ),
    ]
