services:
  vasthood_django:
    container_name: vasthood_django
    build:
      context: ../../
      dockerfile: Dockerfile
    env_file:
      - ../../.env
    tty: true
    ports:
      - "8000:8000"
    networks:
      - dev-net
    volumes:
      - ../../src/apps:/app/apps
      - static_volume:/app/static
      - logs_dir:/app/logs
    healthcheck:
      test: "curl --fail http://localhost:8000/api/healthcheck"
      interval: 20s
      timeout: 2s
      retries: 3
      start_period: 5s

#  celery-beat:
#    container_name: celery-beat
#    build:
#      context: ../../
#      dockerfile: Dockerfile
#    command: [ "-m", "celery", "-A", "services.tasks_.celery_app", "beat", "-l", "info" ]
#    env_file:
#      - ../../.env
#    tty: true
#    networks:
#      - dev-net

  celery-worker:
    container_name: celery-worker
    build:
      context: ../../
      dockerfile: Dockerfile
    command: [ "-m", "celery", "-A", "services.tasks_.celery_app", "worker", "-l", "info" ]
    env_file:
      - ../../.env
    tty: true
    networks:
      - dev-net

networks:
  dev-net:
    name: dev-net
    driver: bridge


volumes:
  static_volume:
    external: true
  logs_dir:
