services:
  main-app:
    image: ${CI_REGISTRY_IMAGE}
    env_file:
      - $env
    tty: true
    ports:
      - "8000:8000"
    networks:
       - nginx-net
       - db-net
       - service-net
    secrets:
      - remote_config
    healthcheck:
      test: "curl --fail http://localhost:8000/api/v1/healthcheck/"
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==prod"
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 30s
        monitor: 120s
      rollback_config:
        parallelism: 0
        order: stop-first


networks:
  nginx-net:
    external: true
  db-net:
    external: true
  service-net:
    external: true