# Generated by Django 5.0.7 on 2024-09-05 12:01

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=16)),
            ],
        ),
    ]
